spring:
  application:
    name: payguard-collateral-service
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    open-in-view: false
  flyway:
    enabled: true
